name: Azure
on: [push]
 
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Azure_Login
        uses: azure/login@v1
        with:
          creds: ${{ secrests.Azure_Credentials }}
